import type { Metadata } from 'next'
import Link from 'next/link'
import { PrintButton } from '@/components/panel/reports/PrintButton'
import { IncidentTable, ReportKpis, UptimeTable } from '@/components/panel/reports/ReportTables'
import { Select } from '@/components/ui/Field'
import { incidentPublishedAt, metricsForRange } from '@/lib/domain/metrics'
import { parseReportPeriod, previousMonth, recentMonths } from '@/lib/domain/schemas/metrics'
import { listSlos } from '@/lib/domain/slos'
import { formatDate, formatDateTime, formatUptime } from '@/lib/format'
import { guard, panelContext, projectAccess } from '@/lib/panel/server'
import '@/styles/panel/reports.css'

export const metadata: Metadata = { title: 'SLA report' }

/** Monthly SLA report: one printable page per calendar month (Print → Save as PDF). */
export default async function SlaReportPage({ params, searchParams }: { params: Promise<{ projectId: string }>; searchParams: Promise<{ month?: string }> }) {
  const { projectId } = await params
  const query = await searchParams
  const access = await projectAccess(projectId)
  const ctx = await panelContext()
  const id = access.project.id
  const timeZone = access.project.timezone || 'UTC'
  const period = parseReportPeriod({ month: query.month ?? previousMonth(timeZone) }, timeZone)
  const [metrics, slos] = await Promise.all([guard(() => metricsForRange(ctx, access, period.from, period.to)), guard(() => listSlos(ctx, id))])
  const publishedAt = await incidentPublishedAt(ctx, id, metrics.incidents.list.map((incident) => incident.id))
  const pageSlo = slos.find((slo) => slo.component_id === null) ?? null
  const months = recentMonths(timeZone)

  return (
    <article className="sla">
      <div className="sla-toolbar no-print">
        <Link className="link" href={`/p/${id}/reports`}>
          Back to reports
        </Link>
        <form className="row" style={{ ['--gap' as string]: '8px' }}>
          <Select name="month" aria-label="Month" defaultValue={period.month ?? undefined} options={months.map((month) => ({ value: month.value, label: month.partial ? `${month.label} (to date)` : month.label }))} />
          <button type="submit" className="btn btn-ghost btn-sm">
            Show
          </button>
        </form>
        <PrintButton />
      </div>
      <header className="sla-head">
        <div className="stack" style={{ ['--gap' as string]: '6px' }}>
          <span className="help">Service level report</span>
          <h1 className="sla-title">{access.project.name}</h1>
          <span className="muted">
            {period.label}, {formatDate(period.from, { timeZone })} to {formatDate(period.partial ? period.to : new Date(period.to.getTime() - 1), { timeZone })} ({timeZone.replace(/_/g, ' ')})
          </span>
        </div>
        <div className="sla-verdict">
          <span className="help">Availability</span>
          <strong className={pageSlo && metrics.uptime < pageSlo.target ? 's-major' : 's-operational'}>{formatUptime(metrics.uptime)}</strong>
          <span className="help">{pageSlo ? `${metrics.uptime >= pageSlo.target ? 'Meets' : 'Misses'} the ${pageSlo.target}% objective` : 'No page-wide objective set'}</span>
        </div>
      </header>
      {period.partial ? <p className="sla-note">This month is not over: figures cover the days so far.</p> : null}
      <ReportKpis metrics={metrics} sloTarget={pageSlo?.target ?? null} />
      <section className="sla-section">
        <h2>Uptime by component</h2>
        <UptimeTable metrics={metrics} />
      </section>
      <section className="sla-section">
        <h2>Incidents</h2>
        <IncidentTable metrics={metrics} publishedAt={publishedAt} timeZone={timeZone} projectId={null} />
      </section>
      <footer className="sla-foot">
        Generated by Upvane on {formatDateTime(new Date(), { timeZone, withZone: true })}. Uptime counts major outages fully and partial outages and degraded performance by the weights set for this status page; maintenance windows do not count as downtime.
      </footer>
    </article>
  )
}
